In [1]:
import numpy as np

In [3]:
a = np.array([[1, 2 , 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [4]:
print(a[0])

[1 2 3 4]


# Array

In [ ]:
# Creating Array
np.array()
np.zeros()
np.ones()
np.empty()
np.arange()

In [5]:
a = np.array([1, 2, 3])

In [6]:
a

array([1, 2, 3])

In [7]:

## you can easily create an array with 0s:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [8]:
## Or an array filled with 1s:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [9]:
## Or even an empty array!
## The function empty creates an array whose initial content is random and depends  on the state of the memory

np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [24]:
## You can create an array with  a range of elements
print(np.arange(4))
print(np.arange(0,10,2)) # (Start, stop, step)

[0 1 2 3]
[0 2 4 6 8]


In [25]:
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

In [ ]:
# Add Remove and short
np.append()
np.delete()
np.sort()

In [26]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
np.append(arr, [1, 2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [28]:
np.delete(arr, [1])

array([1, 3, 4, 5, 6, 7, 8])

In [29]:
arr = np.array([2, 5, 3, 1, 7, 8, 6, 4])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# Shape and Size
ndarray.ndim()
ndarray.size()
ndarray.shape()

In [35]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                           [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [40]:
array_example.ndim

3

In [41]:
array_example.size

32

In [42]:
array_example.shape

(4, 2, 4)

In [43]:
arr_one = np.array([[1, 2, 3, 4, 5]])

In [44]:
arr_one.ndim

2

In [45]:
arr_one.size

5

In [46]:
arr_one.shape

(1, 5)

In [ ]:
# Reshape
np.reshape()

In [48]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [49]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [51]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
# Convert 1D to 2D
np.newaxis()
np.expand_dims()

In [56]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [57]:
## You can use np.newaxis to add new axis

a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [58]:
## You can convert a 1D array to a row vector by  inserting an axis along the first dimension

row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [59]:
## for a column vector, You can insert an axis along the second dimension

col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [64]:
## You can use np.expand_dims to add an exist at index position 1 with:

b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [65]:
## You can add an axis at index position 0 with:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [3]:
# Indexing and Slicing
data = np.array([1,2,3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [4]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
## You can easily print all of the values in the array that are less than 5

print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [6]:
five_up = ( a>= 5)

print(a[five_up])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [7]:
## You can select elements that are divisible by 2

divisible_by_2 = a[a%2==0]

print(divisible_by_2)

[ 2  4  6  8 10 12]


In [8]:
## you can select elements that satisfy two conditions using the & and | operators

c = a[(a > 2) & ( a<11 )]
print(c)

[ 3  4  5  6  7  8  9 10]


In [ ]:
# Creating Array from Existing Data
np.vstack()
np.hstack()
np.hsplit()
.view()
.copy()

In [11]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [12]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [13]:
## Menumpuk dua array
a_1 = np.array([[1, 1],
                [2, 2]])

In [15]:
a_2 = np.array([[3, 3],
                [4, 4]])

In [16]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [17]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [20]:
arrsplit = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])
print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [21]:
## If you wanted to split this array into three equally shaped arrays
np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [22]:
## Shallow copy
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
## You can create a new array object that looks at the same data
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
## using the copy method will make a complete copy of the array and its data ( a deep copy).
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# Basic Array operations
# data - ones
# data * ones
# data / ones

In [2]:
a = np.array([1, 2, 3, 4])
# Add all of the elements in the array
a.sum()

10

In [3]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [4]:
# You can sum the rows
b.sum(axis=0)

array([3, 3])

In [5]:
# you can sum the columns
b.sum(axis=1)

array([2, 4])

In [6]:
data = np.array([1, 2])
data

array([1, 2])

In [7]:
ones = np.ones(2)
ones

array([1., 1.])

In [8]:
data + ones

array([2., 3.])

In [10]:
data * data

array([1, 4])

In [11]:
data / data

array([1., 1.])

In [12]:
# Broadcasting
data * 2

array([2, 4])

In [ ]:
# More Array Operations
data.max()
data.min()
data.sum()

In [13]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [14]:
A.sum()

4.8595784

In [15]:
A.min()

0.05093587

In [19]:
A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [20]:
A.max()

0.82485143

In [21]:
A.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [22]:
A.std()

0.21392120766089617

# Matrices

In [24]:
# Creating Matrices
np.ones((3,2))
np.zeros((3,2))
np.random.random((3,2))

print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.00501538 0.04294981]
 [0.00863872 0.85271998]
 [0.26196515 0.11265472]]


In [25]:
# Matrix Arithmetic
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [27]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [28]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [29]:
ones_row = np.ones([1, 2])
print(ones_row)

[[1. 1.]]


In [30]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


In [31]:
# Dot product
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [32]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

In [33]:
# Matrix Indexing
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


In [34]:
# Matrix Aggregation
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [35]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [36]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


In [37]:
# Transposing and Reshaping
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [38]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [39]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [40]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
data_col.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
arr = np.arange(6).reshape((2, 3))
print(arr)

[[0 1 2]
 [3 4 5]]


In [45]:
# N-Dimensional Array
ndarr = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])

print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [47]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [48]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [49]:
print(np.random.random((4,3,2)))

[[[0.69164213 0.22401214]
  [0.54121959 0.18035272]
  [0.68782598 0.10539768]]

 [[0.09556671 0.31169946]
  [0.47706732 0.6123763 ]
  [0.25021548 0.98203546]]

 [[0.63014431 0.71972338]
  [0.77127531 0.09176271]
  [0.32839882 0.31128219]]

 [[0.82852058 0.31946154]
  [0.69941153 0.57416351]
  [0.41134342 0.14535847]]]


In [50]:
# Flatten N-Dimensional Array
arrflat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [51]:
## You can use flatten to flatten your array into a !D array
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [54]:
# Working with Math Formulas
error = (1/n * np.sum(np.square(observed - prediction)))

NameError: name 'observed' is not defined